# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='filename',
            new_name='propietario',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
